package com.liferay.EmployeeRegister.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Position service. Represents a row in the &quot;Emp_Position&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.EmployeeRegister.service.model.impl.PositionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.EmployeeRegister.service.model.impl.PositionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Position
 * @see com.liferay.EmployeeRegister.service.model.impl.PositionImpl
 * @see com.liferay.EmployeeRegister.service.model.impl.PositionModelImpl
 * @generated
 */
public interface PositionModel extends BaseModel<Position> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a position model instance should use the {@link Position} interface instead.
     */

    /**
     * Returns the primary key of this position.
     *
     * @return the primary key of this position
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this position.
     *
     * @param primaryKey the primary key of this position
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this position.
     *
     * @return the uuid of this position
     */
    @AutoEscape
    public String getUuid();

    /**
     * Sets the uuid of this position.
     *
     * @param uuid the uuid of this position
     */
    public void setUuid(String uuid);

    /**
     * Returns the position ID of this position.
     *
     * @return the position ID of this position
     */
    public long getPositionId();

    /**
     * Sets the position ID of this position.
     *
     * @param positionId the position ID of this position
     */
    public void setPositionId(long positionId);

    /**
     * Returns the name of this position.
     *
     * @return the name of this position
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this position.
     *
     * @param name the name of this position
     */
    public void setName(String name);

    /**
     * Returns the archive of this position.
     *
     * @return the archive of this position
     */
    public boolean getArchive();

    /**
     * Returns <code>true</code> if this position is archive.
     *
     * @return <code>true</code> if this position is archive; <code>false</code> otherwise
     */
    public boolean isArchive();

    /**
     * Sets whether this position is archive.
     *
     * @param archive the archive of this position
     */
    public void setArchive(boolean archive);

    /**
     * Returns the employee ID of this position.
     *
     * @return the employee ID of this position
     */
    public long getEmployeeId();

    /**
     * Sets the employee ID of this position.
     *
     * @param employeeId the employee ID of this position
     */
    public void setEmployeeId(long employeeId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.liferay.EmployeeRegister.service.model.Position position);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.liferay.EmployeeRegister.service.model.Position> toCacheModel();

    @Override
    public com.liferay.EmployeeRegister.service.model.Position toEscapedModel();

    @Override
    public com.liferay.EmployeeRegister.service.model.Position toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
