package com.liferay.EmployeeRegister.service.model.impl;

import com.liferay.EmployeeRegister.service.model.Bank;
import com.liferay.EmployeeRegister.service.model.BankModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Bank service. Represents a row in the &quot;Emp_Bank&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.EmployeeRegister.service.model.BankModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BankImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BankImpl
 * @see com.liferay.EmployeeRegister.service.model.Bank
 * @see com.liferay.EmployeeRegister.service.model.BankModel
 * @generated
 */
public class BankModelImpl extends BaseModelImpl<Bank> implements BankModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a bank model instance should use the {@link com.liferay.EmployeeRegister.service.model.Bank} interface instead.
     */
    public static final String TABLE_NAME = "Emp_Bank";
    public static final Object[][] TABLE_COLUMNS = {
            { "uuid_", Types.VARCHAR },
            { "bank_id", Types.BIGINT },
            { "name", Types.VARCHAR },
            { "bik", Types.VARCHAR },
            { "address", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table Emp_Bank (uuid_ VARCHAR(75) null,bank_id LONG not null primary key,name VARCHAR(75) null,bik VARCHAR(75) null,address VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table Emp_Bank";
    public static final String ORDER_BY_JPQL = " ORDER BY bank.bankId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY Emp_Bank.bank_id ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.liferay.EmployeeRegister.service.model.Bank"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.liferay.EmployeeRegister.service.model.Bank"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.liferay.EmployeeRegister.service.model.Bank"),
            true);
    public static long UUID_COLUMN_BITMASK = 1L;
    public static long BANKID_COLUMN_BITMASK = 2L;
    public static final String MAPPING_TABLE_EMP_BANKS_EMPLOYEES_NAME = "Emp_Banks_Employees";
    public static final Object[][] MAPPING_TABLE_EMP_BANKS_EMPLOYEES_COLUMNS = {
            { "bank_id", Types.BIGINT },
            { "employee_id", Types.BIGINT }
        };
    public static final String MAPPING_TABLE_EMP_BANKS_EMPLOYEES_SQL_CREATE = "create table Emp_Banks_Employees (bank_id LONG not null,employee_id LONG not null,primary key (bank_id, employee_id))";
    public static final boolean FINDER_CACHE_ENABLED_EMP_BANKS_EMPLOYEES = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.Emp_Banks_Employees"), true);
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.liferay.EmployeeRegister.service.model.Bank"));
    private static ClassLoader _classLoader = Bank.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] { Bank.class };
    private String _uuid;
    private String _originalUuid;
    private long _bankId;
    private String _name;
    private String _bik;
    private String _address;
    private long _columnBitmask;
    private Bank _escapedModel;

    public BankModelImpl() {
    }

    @Override
    public long getPrimaryKey() {
        return _bankId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setBankId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _bankId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Bank.class;
    }

    @Override
    public String getModelClassName() {
        return Bank.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("uuid", getUuid());
        attributes.put("bankId", getBankId());
        attributes.put("name", getName());
        attributes.put("bik", getBik());
        attributes.put("address", getAddress());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        String uuid = (String) attributes.get("uuid");

        if (uuid != null) {
            setUuid(uuid);
        }

        Long bankId = (Long) attributes.get("bankId");

        if (bankId != null) {
            setBankId(bankId);
        }

        String name = (String) attributes.get("name");

        if (name != null) {
            setName(name);
        }

        String bik = (String) attributes.get("bik");

        if (bik != null) {
            setBik(bik);
        }

        String address = (String) attributes.get("address");

        if (address != null) {
            setAddress(address);
        }
    }

    @Override
    public String getUuid() {
        if (_uuid == null) {
            return StringPool.BLANK;
        } else {
            return _uuid;
        }
    }

    @Override
    public void setUuid(String uuid) {
        if (_originalUuid == null) {
            _originalUuid = _uuid;
        }

        _uuid = uuid;
    }

    public String getOriginalUuid() {
        return GetterUtil.getString(_originalUuid);
    }

    @Override
    public long getBankId() {
        return _bankId;
    }

    @Override
    public void setBankId(long bankId) {
        _bankId = bankId;
    }

    @Override
    public String getName() {
        if (_name == null) {
            return StringPool.BLANK;
        } else {
            return _name;
        }
    }

    @Override
    public void setName(String name) {
        _name = name;
    }

    @Override
    public String getBik() {
        if (_bik == null) {
            return StringPool.BLANK;
        } else {
            return _bik;
        }
    }

    @Override
    public void setBik(String bik) {
        _bik = bik;
    }

    @Override
    public String getAddress() {
        if (_address == null) {
            return StringPool.BLANK;
        } else {
            return _address;
        }
    }

    @Override
    public void setAddress(String address) {
        _address = address;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            Bank.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Bank toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Bank) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        BankImpl bankImpl = new BankImpl();

        bankImpl.setUuid(getUuid());
        bankImpl.setBankId(getBankId());
        bankImpl.setName(getName());
        bankImpl.setBik(getBik());
        bankImpl.setAddress(getAddress());

        bankImpl.resetOriginalValues();

        return bankImpl;
    }

    @Override
    public int compareTo(Bank bank) {
        long primaryKey = bank.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Bank)) {
            return false;
        }

        Bank bank = (Bank) obj;

        long primaryKey = bank.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        BankModelImpl bankModelImpl = this;

        bankModelImpl._originalUuid = bankModelImpl._uuid;

        bankModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Bank> toCacheModel() {
        BankCacheModel bankCacheModel = new BankCacheModel();

        bankCacheModel.uuid = getUuid();

        String uuid = bankCacheModel.uuid;

        if ((uuid != null) && (uuid.length() == 0)) {
            bankCacheModel.uuid = null;
        }

        bankCacheModel.bankId = getBankId();

        bankCacheModel.name = getName();

        String name = bankCacheModel.name;

        if ((name != null) && (name.length() == 0)) {
            bankCacheModel.name = null;
        }

        bankCacheModel.bik = getBik();

        String bik = bankCacheModel.bik;

        if ((bik != null) && (bik.length() == 0)) {
            bankCacheModel.bik = null;
        }

        bankCacheModel.address = getAddress();

        String address = bankCacheModel.address;

        if ((address != null) && (address.length() == 0)) {
            bankCacheModel.address = null;
        }

        return bankCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(11);

        sb.append("{uuid=");
        sb.append(getUuid());
        sb.append(", bankId=");
        sb.append(getBankId());
        sb.append(", name=");
        sb.append(getName());
        sb.append(", bik=");
        sb.append(getBik());
        sb.append(", address=");
        sb.append(getAddress());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(19);

        sb.append("<model><model-name>");
        sb.append("com.liferay.EmployeeRegister.service.model.Bank");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>uuid</column-name><column-value><![CDATA[");
        sb.append(getUuid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>bankId</column-name><column-value><![CDATA[");
        sb.append(getBankId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>name</column-name><column-value><![CDATA[");
        sb.append(getName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>bik</column-name><column-value><![CDATA[");
        sb.append(getBik());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>address</column-name><column-value><![CDATA[");
        sb.append(getAddress());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
